### ISSUE TITLE
raspberrypi run error, It is recommended to provide a demo

### ISSUE THREAD

**Issue by May-Yaha** [NoxInmortus/docker-ldap-tool-box#3]
Linux raspberrypi 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux

log:

```shell
mode of '/etc/apache2/sites-available/000-default.conf' retained as 0640 (rw-r-----)
...generating temporary LDAP_KEYPHRASE.
/usr/bin/phplint: line 1: Not: command not found
```

docker-compose.yml:

```yml
version: "2"
services: 
  ldap-server:
    hostname: flyaha.openldap
    image: osixia/openldap
    container_name: ldap-server
    ports: 
      - 389:389
      - 636:636
    environment:
      - LDAP_ORGANISATION=flyaha
      - LDAP_DOMAIN=flyaha.top
      - LDAP_ADMIN_PASSWORD=MhxzKhl@2021
    restart: always
  ldap-manager:
    image: osixia/phpldapadmin:latest
    container_name: ldap-manager
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-server
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8001:80"
    depends_on:
      - ldap-server
    restart: always
  ldap-ssp:
    hostname: ssp.flyaha.top
    image: noxinmortus/docker-ldap-tool-box:self-service-password
    container_name: ldap-ssp
    environment:
      - LDAP_URL=ldap://ldap-server
      - LDAP_BINDDN=cn=admin,dc=flyaha,dc=top
      - LDAP_BINDPW=MhxzKhl@2021
      - LDAP_BASE=cn=users,dc=flyaha,dc=top
      - LDAP_MAIL_FROM=xxx
      - LDAP_SMTP_DEBUG=0
      - LDAP_SMTP_HOST=xxx
      - LDAP_SMTP_USER=xxx
      - LDAP_SMTP_PASS=xxx
      - LDAP_SMTP_PORT=465
      - LDAP_SMTP_SECURE=ssl
      - LDAP_SMTP_AUTOTLS=true
    restart: always
    ports:
      - "8004:80"
    depends_on:
      - ldap-server
networks:
  default:
    external:
      name: dev
```
